# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ea9cb88576c662193cac7695131559316b842bd0d898595dcbff3b2a64999a6c30106efe1be1875f373ce39fe92efa8591a1d7b4cd97166e64a5914fad92e6e

test:
  secret_key_base: b6c0e6b2bc56c65686ad523599f6b325ed5f1aa2782b66b58da172f62d01d4057892bf7a83e1a35c8b6a3381d6f1ad09b4172e61b45390dbefa71c200ca6f8a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
